### ISSUE TITLE
`Encoding::encode_mut` is very code-size heavy 

### ISSUE THREAD

**Issue by GnomedDev** [ia0/data-encoding#97] opened 2024-02-01 22:08 UTC
Hello, I've just ran [cargo-bloat](https://github.com/RazrFalcon/cargo-bloat) on my [project](https://github.com/Discord-TTS/Bot) as I'm working on reducing compile times and binary sizes can be a proxy for compile times, and found that `data_encoding::Encoding::encode_mut` is taking up `76.9kb` , the third largest function in my entire project (that pulls reqwest, tungstenite, etc).

If code size isn't a concern for this project, I'm entirely fine with this being closed, but thought that you might want a heads up that this library is somewhat code-size heavy.

**Comment by ia0** [comment] 2024-02-01 22:31
Thanks for opening an issue! Yes, binary size is a concern for this library, but only with LTO (because it heavily relies on the actual encoding being known at compile time). Are you measuring bloat with full LTO enabled? If yes, could you provide me reproduction steps? There wasn't any heavy benchmarks in that regard and also no CI to check for regressions, so might be a valid issue :-/

**Comment by GnomedDev** [comment] 2024-02-01 23:10
The reproduction I have is that project, but I don't have enough energy to look into this much further. It uses thin lto, but it's probably a bad idea to rely on LTO in the first place. My suggestion would be to feature-lock each encoding to allow dependents to only enable what they need, avoiding the need to rely on LTO.

**Comment by ia0** [comment] 2024-02-18 17:49
I'm back from vacation and could take a look. However I'm not able to reproduce. I tried `cargo bloat --release` in your repo but I only see:

```
0.0%   0.1%  16.1KiB   data_encoding data_encoding::Encoding::encode_mut
```

Could you provide me with exact instructions to reproduce (including commit hash). I have an idea that could easily fix the issue but I want to confirm it actually fixes your problem first.

Thanks!

**Comment by lambdadeltakay** [comment] 2024-03-04 06:36
![image](https://github.com/ia0/data-encoding/assets/144762384/c4a0d539-277f-41d5-ab74-38cb703c54da)

My project also gets this for the encoding and decoding function

Relevant usage of the library

```rust
#[derive(Clone, Copy, Hash, PartialEq, Eq, PartialOrd, Ord, Debug, Serialize, Deserialize)]
pub struct PublicKey(pub [u8; 32]);

impl Display for PublicKey {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&HEXLOWER_PERMISSIVE.encode(&self.0))
    }
}

impl FromStr for PublicKey {
    type Err = RouteWeaverError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        Ok(PublicKey(
            HEXLOWER_PERMISSIVE
                .decode(s.as_bytes())
                .map_err(|_| RouteWeaverError::KeyFailedToParse)?
                .try_into()
                .map_err(|_| RouteWeaverError::KeyFailedToParse)?,
        ))
    }
}

#[derive(PartialEq, Eq, PartialOrd, Ord, Debug, Serialize, Deserialize, ZeroizeOnDrop)]
pub struct PrivateKey(pub [u8; 32]);

impl Display for PrivateKey {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&HEXLOWER_PERMISSIVE.encode(&self.0))
    }
}

impl FromStr for PrivateKey {
    type Err = RouteWeaverError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        Ok(PrivateKey(
            HEXLOWER_PERMISSIVE
                .decode(s.as_bytes())
                .map_err(|_| RouteWeaverError::KeyFailedToParse)?
                .try_into()
                .map_err(|_| RouteWeaverError::KeyFailedToParse)?,
        ))
    }
}
```

**Comment by ia0** [comment] 2024-03-23 13:34
Sorry for the long delay. I tried to `#[inline(always)]` the API but the dead code is still not eliminated, so I went with the manual solution of providing features. In the `route-weaver-router` reproduction case, this means changing the dependency from:

```toml
[dependencies]
data-encoding = "2.5"
```

to:

```toml
[dependencies.data-encoding]
version = "2.6"  # not released yet
default-features = false
features = ["std", "base16"]
```

The code size measured with the text column of `cargo size -p route-weaver-router --release` reduces from 2029548 to 1965156 bytes (64392 less). The data-encoding functions measured with `cargo bloat -p route-weaver-router --release --crates -n50 | grep data_encoding` reduce from 72.2KiB to 12.6KiB (59.6KiB less).

It is probably possible to do better but it would require quite some refactoring. Would this change be enough for you?

The change is in #101 and I'll keep it open until I decide whether it should be a breaking change or not. It is technically one for those who disable default features.

**Comment by ia0** [comment] 2024-03-24 20:58
Actually, I'll probably postpone submitting that PR until I experiment with another idea that would bring much more benefit. I'm just afraid that it might make the API a bit less usable by having many type parameters (a little bit like RustCrypto does). Because if I'll have to make a major version bump, then let's try to make the most out of it.

**Comment by lambdadeltakay** [comment] 2024-03-25 15:39
Thank you for looking into it

**Comment by ia0** [comment] 2024-03-29 23:48
Ok, my experiment using `StaticEncoding<B: Static<usize>>` (and making `Encoding` a dyn object) seems to provide similar benefits, but doesn't need features. It might still be a breaking change because I'll have to change the constants from `const` to `static`. This also would need more work, so not sure how long it will take.

**Comment by lambdadeltakay** [comment] 2024-03-30 04:24
Do you think this is working around a LLVM quirk?

**Comment by ia0** [comment] 2024-03-30 12:09
I don't think so. The current design assumes inlining and dead-code elimination to work cross-crate. This seems to work rather well with LTO but not otherwise. The new design I have in mind (I didn't fully test it though) doesn't rely on inlining by adding one layer of indirection (which can be optimized by inlining) and simplifies dead-code elimination by introducing a symbol for each combination, so the linker can always do it regardless of LTO.

**Comment by lambdadeltakay** [comment] 2024-03-31 00:01
Ahh I see. Well thank you for figuring it out

**Comment by ia0** [comment] 2024-04-28 20:32
Ok, I got some time to look into this again. I've created the `v3-preview` branch for now. It will eventually be merged in the `main` branch. It essentially provides a `v3-preview` feature that provides a `v3_preview` module. This module would eventually be the 3.0.0 of `data-encoding` (but for now is unstable and uses a higher MSRV).

I did the following change:

```diff
diff --git a/common/Cargo.toml b/common/Cargo.toml
-data-encoding = "2.5"
+data-encoding = { git = "https://github.com/ia0/data-encoding.git", branch = "v3-preview", features = ["v3-preview"] }
diff --git a/common/src/noise.rs b/common/src/noise.rs
-use data_encoding::HEXLOWER_PERMISSIVE;
+use data_encoding::v3_preview::HEXLOWER_PERMISSIVE;
```

For the following measurements:

| | cargo size | cargo bloat |
|---|---|---|
| before | 2093644 | 72.1KiB |
| after | 2017828 | 219B |
| diff | 75816 | 73611 |

Where "cargo size" is `cargo size -p route-weaver-router --release` and "cargo bloat" is `cargo bloat -p route-weaver-router --release --crates -n100 | grep data_encoding`.

So this looks pretty good so far. I'll have to finish adding all features to the `v3_preview` module and see if I want to add other things. I'll ping here when the `v3-preview` branch makes it to `main`, then I'll wait a month or so and do a release, at which point I'll probably close this issue.

**Comment by lambdadeltakay** [comment] 2024-04-29 03:43
Thank you, this is very cool. I am redoing my project and planned to use data-encoding for other things than printing and parsing public/private keys so the added efficiency is amazing.

**Comment by ia0** [comment] 2024-05-05 14:49
This is now merged in `main`. It will eventually be part of 3.0.0 (tracked by #106) but will probably be released as a "preview" module too (to catch possible usability issues).

**Closed by ia0** 2024-05-05 14:49 UTC
